export default[
  {id:1,
    projectName:"Scroller",
  description:"Simple app to allow the user to enter text and then display it as scrolling text when they rotate their screen- optimised for viewing on phones or via devtools",
  detailedDescription:"Scroller was developed from an idea I had for a simple application to present quick and easy scrolling text. Working with my friend Jack Portwood, we iterated through the app many times to get the end product. This was a terrific project that helped upskill me on React, React Hooks, and optimising for phones.",
  image:"Images/scroller.jpeg",
  className:"small",link:"https://scrollingapp.netlify.app"},
  {id:2,
    projectName:"SpaceX Launcher",
    description:"Fetches data from SpaceX api and displays the details about the launch. Incorporates filter and sort functions",
    detailedDescription:"Initially produced 'to spec' from a technical test for a job, the lack of guidance on content and format allowed me to tackle the key sort/filter functions using custom code by me.",
    image:"Images/spacex.jpeg",
    className:"large",link:"https://sutherlandspacex.netlify.app"},
{id:3,
  projectName:"ISS Tracker",
  description:"Fetches positional information for the International Space Station and displays a map of its path in real time",
  detailedDescription:"This was a project I built for fun. I challanged myself to build it in a day, and the majority was complete in a few hours. My first 'hosted' application. Uses a fetch from an API to get real-time co-ordinates and generate a path showing where the ISS has been.",
  image:"Images/iss.jpeg",
  className:"large",link:"https://sutherland-iss.netlify.app"}]
